- docs/changelog.rst
- mopidy/audio/playlists.py
- tests/audio/test_playlists.py
Non-ascii utf-8 chars in a .m3u playlist will cause an error similar to the following:
> 2015-01-02 17:22:31,232 - ERROR    GStreamer encountered a general supporting library error. Debug message: /usr/local/lib/python2.7/dist-packages/mopidy/audio/playlists.py(212): _event (): /GstPlayBin2:playbin20/GstURIDecodeBin:uridecodebin4/GstDecodeBin2:decodebin21/mopidy+audio+playlists+M3uDecoder:mopidy+audio+playlists+m3udecoder1:
<type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
This error only occurs if you **don't** enable the mopidy-mpris extension (#853 for more details). 
I added utf-8 characters to all the test playlists even though the other parsers use libraries rather than directly manipulating the bytestrings and are …
> Support utf-8 chars in m3u playlists

- mopidy/local/search.py
- tests/local/test_search.py
Fixes an issue in exact search so it handles filtering over Tracks where a Track's album is None (see #930).
> local: Fix exact search to handle tracks where album is None

- mopidy/commands.py
- mopidy/core/actor.py
- mopidy/core/listener.py
- mopidy/core/playback.py
- mopidy/mpd/actor.py
- mopidy/mpd/protocol/current_playlist.py
- mopidy/mpd/protocol/status.py
- mopidy/mpd/translator.py
> Propagate stream metadata

- mopidy/audio/actor.py
> Re-set volume explicitly to the current level whenever changing tracks.

- docs/changelog.rst
- mopidy/local/__init__.py
- mopidy/local/commands.py
@tkem couldn't quite make my mind up to if the API should passing in `add(track)` for "legacy" clients and then `add(uri, tags, duration)` for new ones, so ended up with this mix. To be honest I don't care exactly which variant we go with as long as it solves the use case you had :-)
> Add tags and duration to local library add()

- docs/changelog.rst
- mopidy/backend/__init__.py
- mopidy/core/library.py
- mopidy/models.py
- tests/core/test_library.py
- tests/test_models.py
Fixes #973 and #838 - followup will be to start deprecating the old images in models.
> Add library.get_images()

- docs/changelog.rst
- docs/ext/mpd.rst
- mopidy/mpd/__init__.py
- mopidy/mpd/dispatcher.py
- mopidy/mpd/exceptions.py
- mopidy/mpd/ext.conf
- mopidy/utils/deprecation.py
- tests/mpd/test_dispatcher.py
Default blacklist set to listall and listallinfo.
This change has been done to avoid clients being able to call "bad" MPD
commands which are often misused to try and keep a client db. Note that
this change will break some MPD clients, but the blacklist can be controlled
via config to allow opting out for now.
This is relevant as a first step in the direction suggested in https://github.com/mopidy/mopidy/issues/686#issuecomment-64089734 which advocates getting rid of the commands all together.
> mpd: Support blacklisting MPD commands in the server.

- mopidy/local/playlists.py
- mopidy/local/translator.py
- tests/local/test_playlists.py
> Fix #937: Local playlists refactoring.

- mopidy/backend.py
- tests/backend/test_backend.py
This slightly improves the new default `get_images()` implementation when called with album or artist URIs. An album or artist URI `lookup` may result in multiple tracks which will probably share the same album(s), resulting in duplicate image URIs being reported. With this patch, image URIs belonging to all tracks reported for a given input URI are put into a set first, thus eliminating duplicates.
As a side effect, the default implementation now returns an empty list if no images can be found.
> Improve default get_images() implementation with album/artist URIs.

- docs/changelog.rst
- mopidy/backend.py
- mopidy/core/library.py
- mopidy/local/__init__.py
- mopidy/local/json.py
- mopidy/local/library.py
- mopidy/mpd/protocol/music_db.py
- tests/dummy_backend.py
- tests/mpd/protocol/test_music_db.py
Should resolve part of the problem with #913 as this gives backends a way to support this other than doing our silly search for everything workaround.
> Add list_distinct command for more effective library lookups.

- mopidy/core/actor.py
- mopidy/core/tracklist.py
- mopidy/local/json.py
- mopidy/local/search.py
- tests/local/test_json.py
Fixes the json local library's search behavior by adding support for limit and offset parameters to search helpers. Currently, `JsonLibrary.search` returns all matching results, and ignores the limit and offset parameters. (see #917)
----
Note: LocalLibraryProvider [does not pass any limit/offset arguments][llp] when searching its local backend (which has [a default limit of 100 and offset of 0][search]). When using mopidy as a mpd server, this affects how many results [the `list` command][list] returns:
([mpd backend]: [result of `$ mpc list artist | wc -l`])
mpd: 1033
mopidy (develop): 1031
mopidy (fix/local-json-limit-offset): 86
[llp]: https://github.com/mopidy/mopidy/blob/develop/mopidy/local/library.py#L44
[search]: https://docs.mopidy.com/en/latest/modules/local/#mopidy.local.Librar …
> local: add limit and offset support to json library search helpers

- docs/changelog.rst
- mopidy/local/commands.py
- mopidy/local/translator.py
- tests/local/test_translator.py
As discussed in #1023, the current implementation adds a link to `track.album.images` without checking if the corresponding image exists in the Cover Art Archive.
Since `album.images` is going to be deprecated anyway and replaced with `Library.get_images()`, the easiest solution is to simply remove this for now.
> Fix #1023: Remove support for local album images from coverartarchive.org

- docs/changelog.rst
- mopidy/local/playlists.py
- tests/local/test_playlists.py
Fixes #1026 by sorting the local playlists according to their `name` property after every `create`, `save` and `refresh` operation. Slightly inefficient, but this should be converted to use a `{uri: playlist}` mapping after `get_playlists()` gets implemented, anyway.
> Fix #1026: Sort local playlists by name.

- docs/changelog.rst
- mopidy/local/__init__.py
- mopidy/local/library.py
- tests/local/test_library.py
Fixes #1031 by adding `local.Library.get_images()`, with default implementation corresponding to `LibraryProvider.get_images()`.
> Fix #1031: Add get_images() to local library.

- docs/changelog.rst
- docs/config.rst
- mopidy/commands.py
- mopidy/core/mixer.py
- mopidy/mpd/protocol/audio_output.py
- mopidy/mpd/protocol/playback.py
- tests/core/test_listener.py
- tests/core/test_mixer.py
- tests/dummy_mixer.py
- tests/mpd/protocol/__init__.py
- tests/mpd/protocol/test_audio_output.py
- tests/mpd/protocol/test_idle.py
- tests/mpd/protocol/test_playback.py
- tests/mpd/test_exceptions.py
To disable mixing altogether, you can now let the configuration value
audio/mixer be empty or set it to 'none'.
Fixes #936
> Allow empty or 'none' as audio.mixer value

- docs/changelog.rst
- mopidy/audio/scan.py
- mopidy/local/commands.py
- mopidy/stream/actor.py
- tests/audio/test_scan.py
With this in place we can scan a playlist without our playlist elements installed, check if it's `text/*` or `application/xml` try and `urlopen` it and parse it as a playlist (that is until we switch to totemplparser) without any gstreamer element magic.
This also improves:
- Missing plugin messages on errors.
- Seekable lookup which I want to try and use.
- Got rid of some code that wasn't really doing much for us.
Changelog entry will be forthcoming tomorrow :-)
> Add typefinding / MIME guess to scan code.

- docs/changelog.rst
- mopidy/models.py
- mopidy/utils/path.py
> models: Change Track.last_modified from seconds to ms

- docs/changelog.rst
- mopidy/local/__init__.py
- tests/local/test_library.py
Fix for PR #1032: Ignored the fact that local libraries could still return a single track from `lookup()` for backward-compatibility; results in 
```
File "/home/tkemmer/src/mopidy/mopidy/local/library.py", line 34, in get_images
return self._library.get_images(uris)
File "/home/tkemmer/src/mopidy/mopidy/local/__init__.py", line 119, in get_images
for track in self.lookup(uri):
TypeError: 'Track' object is not iterable
```
> local: Fix get_images() for local libraries returning single track from lookup().

- mopidy/core/playback.py
- mopidy/models.py
- mopidy/mpd/translator.py
- tests/core/test_playback.py
- tests/mpd/test_translator.py
Seeks will now fail when the duration is None, this is an approximation to if
the track is seekable or not. This check is need as otherwise seeking a radio
stream will trigger the next track.
If the track truly isn't seekable despite having a duration we should still
fail as GStreamer will reject the seek.
> core: Correctly handle missing duration in seek.

- mopidy/core/actor.py
- tests/core/test_playback.py
- tests/dummy_audio.py
This is done by checking for the presence of the organization tag typically set
by web streams. This might be a bit to strict and a bad heuristic, but it's
currently better than wrongly emitting stream titles for non streams IMO.
> core: Only emit stream title changed for streams

- docs/changelog.rst
- mopidy/utils/network.py
- mopidy/utils/path.py
I reviewed all instances of:
- EnvironmentError
- OSError
- IOError
- socket.error
In most cases, we already used encoding.locale_decode().
The case fixed in mopidy/utils/network.py fixes #971.
The case fixed in mopidy/utils/path.py might be triggered during a
local library scan.
> Decode all strerror-based exception messages

- docs/changelog.rst
- mopidy/backend.py
- mopidy/local/playlists.py
- tests/backend/test_backend.py
- tests/dummy_backend.py
The default was insane. For one, because overriding e.g. just the
getter would make the property have a pair of working getter and
setter that are entirely disconnected.
> backend: Remove default impl of PlaylistProvider.playlists

- docs/changelog.rst
- mopidy/core/library.py
- tests/core/test_library.py
For now this doesn't add any corresponding APIs to backends, or for that matter
tracklist.add(uris). This is just to get the API in for clients in 0.20.
> core: Add uris argument to library.lookup (Fixes #1008)

- docs/changelog.rst
- mopidy/core/history.py
- mopidy/core/playback.py
- tests/core/test_history.py
Instead of changing the signature to add(uri, name) I opted for
renaming it to _add_track(track).
Since it's internal we may change it whenever we like to. Since you need
different logic for extracting an interesting name from a track and from
a ref or a stream title, it makes sense to add another method for adding
refs/stream titles to the history when that time comes.
Fixes #1056
> core: Make history.add() private

- docs/changelog.rst
- mopidy/core/library.py
- mopidy/core/tracklist.py
- tests/core/test_library.py
- tests/core/test_tracklist.py
> Add uris kwarg to tracklist.add()

- docs/changelog.rst
- docs/ext/m3u.rst
- docs/index.rst
- mopidy/local/__init__.py
- mopidy/local/actor.py
- mopidy/local/ext.conf
- mopidy/local/storage.py
- mopidy/local/translator.py
- mopidy/m3u/__init__.py
- mopidy/m3u/actor.py
- mopidy/m3u/ext.conf
- mopidy/m3u/library.py
- mopidy/m3u/playlists.py
- mopidy/m3u/translator.py
- setup.py
- tests/m3u/__init__.py
- tests/m3u/test_playlists.py
- tests/m3u/test_translator.py
> m3u: Extract new M3U backend from local

- docs/changelog.rst
- mopidy/backend.py
- mopidy/core/playback.py
- mopidy/local/playback.py
- tests/core/test_playback.py
- tests/dummy_backend.py
- tests/local/test_playback.py
While trying to remove traces of stop calls in core to get gapless working I
found we had no way to switch to switch tracks without triggering a play. This
change fixes this by changing the backends playback provider API.
- play() now _only_ starts playback and does not take any arguments.
- prepare_change() has been added, this could have been avoided with a kwarg to
change_track(track), but that would break more backends.
- core has been updated to call prepare_change+change_track+play as needed.
- tests have been updated to handle this change.
Longer term I hope to completely rework the playback API in backends, as 99% of
our backends only use change_track(track) to translate URIs. So we should make
simple case simple, and handle mopidy-spotify / appsrc in some other way.
Cherry picked …
> backend: Change playback API (breaking change!)

- docs/changelog.rst
- mopidy/core/playback.py
- tests/core/test_playback.py
This change has us checking the return value of change_track when deciding if
the play call was a success or if the track is unplayable. Which ensures that
the following can no longer happen: 1) play stream 2) play stream that fails
change_track 3) stream 1) continues playing. Correct behavior being the next
stream playing instead.
> core: Update playback code to take change track into account.

- docs/changelog.rst
- mopidy/core/library.py
- mopidy/local/search.py
- tests/core/test_library.py
This is needed as otherwise each and every backend needs to handle the fact
that some "bad" clients might send {'field': 'value'} instead of
{'field': ['value']} Though the real problem isn't the clients but our
organically grown query API.
> core: Normalize search queries

- mopidy/core/playback.py
- tests/core/test_playback.py
We could possibly also try and do this setup time instead? Using inspect to see we can bind the old signature?
> core: Protect against old clients that implement backend.play

- docs/changelog.rst
- mopidy/core/actor.py
- mopidy/core/playback.py
- mopidy/core/tracklist.py
- tests/core/test_playback.py
- tests/local/test_playback.py
Note that the original goal was just #1070 - but I've done a bit more. As such I've left the changelog out for now as we might want to rebase this dropping some of these changes...
> Remove a bunch of API surface from core

- docs/changelog.rst
- mopidy/backend.py
- mopidy/core/playlists.py
- mopidy/m3u/playlists.py
- tests/backend/test_backend.py
- tests/core/test_playlists.py
- tests/dummy_backend.py
- tests/m3u/test_playlists.py
> Add new playlists API

- docs/changelog.rst
- mopidy/backend.py
- mopidy/core/library.py
- tests/core/test_library.py
Functionality has been replaced with an `exact` param in the search method.
Backends that still implement find_exact will continue being called via
the old method for now.
> core/backend: Remove find_exact from backends

- docs/changelog.rst
- mopidy/core/library.py
- tests/core/test_library.py
Backends that still implement find_exact will be called without exact as an
argument to search, and we will continue to use find_exact. Please remove
find_exact from such backends and switch to the new search API.
> core: Add exact to search() and deprecate find_exact()

- mopidy/core/library.py
- mopidy/local/library.py
- tests/core/test_library.py
- tests/dummy_backend.py
All backends are expected to support the exact argument. A friendly log message
will be printed to prompt users to upgrade backends that fail due to this.
> core/backend: Stop supporting old search signatures

- docs/changelog.rst
- mopidy/m3u/playlists.py
- tests/m3u/test_playlists.py
Reflecting what MPD does to playlist names; also stripping the name provided by the user, since leading/trailing spaces may easily creep in via the UI.
> m3u: Replace slashes in playlist names with pipes.

- docs/changelog.rst
- mopidy/audio/actor.py
Replaces PR #1099 and fixes #1097
> Delayed volume fixes

- docs/changelog.rst
- mopidy/__init__.py
- mopidy/__main__.py
- mopidy/listener.py
- mopidy/utils/path.py
- mopidy/utils/xdg.py
- tests/utils/test_xdg.py
This fixes #1068 for backends. I'll open a new issue for frontends, which we'll have to defer to 2.0.
> Enable testing of backends with global site-packages disabled

- docs/changelog.rst
- mopidy/http/handlers.py
The problem presents itself when a JSON-RPC call triggers some event in core.
When this happens we have a thread outside of Tornado call `write_message`
interleaved with a potentially ongoing write if the JSON-RPC response.
To avoid this we now follow Tornado best practices and add callbacks to the
IOLoop to ensure that there isn't any interleaved access of Tornado state.
> http: Fix threading issue causing duplicate WS messages

- mopidy/core/tracklist.py
- mopidy/utils/deprecation.py
- tests/core/test_tracklist.py
- tests/local/test_tracklist.py
> Support / use TLID in core tracklist calls

- docs/api/models.rst
- mopidy/models/__init__.py
- mopidy/models/fields.py
- mopidy/models/immutable.py
- mopidy/models/serialize.py
- tests/models/test_fields.py
- tests/models/test_legacy.py
- tests/models/test_models.py
Makes sure we don't break existing clients. Tested with mopidy-podcast as it is currently the only known case outside of the `SpotifyTrack` hack in mopidy -spotify.
> Move new models features to new class

- docs/changelog.rst
- mopidy/core/playlists.py
- tests/core/test_playlists.py
Rebased for v1.0.5 (I assume).
> Fix #1162: Ignore None results and exceptions from PlaylistsProvider.create().

- docs/modules/local.rst
- mopidy/local/playback.py
- mopidy/local/translator.py
- tests/local/test_translator.py
To be used by Mopidy-Local-Sqlite instead of `mopidy.utils.path`, which was renamed in #1173.
> Brush up local URI/path helpers

- docs/changelog.rst
- mopidy/m3u/playlists.py
- mopidy/m3u/translator.py
- tests/m3u/test_playlists.py
Fixes #1175. Reserved further refactorings and (possibly) addition of M3U8 support for v1.1.
> m3u: Fix encoding error when saving playlists with non-ASCII track titles

- mopidy/__main__.py
- mopidy/commands.py
- mopidy/config/__init__.py
- mopidy/ext.py
- tests/test_ext.py
Note that I'm actually not doing any error checking on commands, as we need them a bit to early with the current code flow. Also note that the we only check that the default config is truthy, we might want to be more strict about this.
First part of fixing #1148 - following step will be checking config handling, and then finally `setup` and the actually actor startups.
> Make initial bootstrapping handle bad extensions

- docs/changelog.rst
- mopidy/mpd/protocol/music_db.py
- tests/mpd/protocol/test_music_db.py
Hello,
currently the MPD `count` command will raise a `TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'` if one or more of the tracks has no length, in other words, the length is the default value `None`. This happens if a library provider does not provide track length information.
This is an attempt to fix this issue.
> mpd: Ignore tracks without length in the "count" command

- docs/running.rst
As discussed on IRC, mention `mopidy local update` and the curl command early in the docs. Would this be OK?
> docs: describe the library update steps

- mopidy/mpd/protocol/__init__.py
- mopidy/mpd/translator.py
- tests/mpd/test_translator.py
Since mpd 0.19, it has concatenated multiple values using
a ';' character. Mopidy has been using ', '. This makes mopidy
use a ';' for all artist-related values.
In mpd 0.18, multiple values were displayed as multiple lines in
the output, hence this change bumps the mpd protocol version to
0.19 to reflect the new behaviour.
> mpd:Update protocol version to 0.19

- mopidy/core/ext.conf
- mopidy/core/ext.py
- mopidy/core/tracklist.py
- mopidy/exceptions.py
- tests/core/test_events.py
- tests/core/test_playback.py
- tests/core/test_tracklist.py
- tests/local/test_playback.py
- tests/local/test_tracklist.py
- tests/mpd/protocol/__init__.py
- tests/mpd/test_status.py
Added in the check to the add method in core/tracklist.py, added the schema to core/actor.py, and added the max_tracklist_length to the config file. Even if the config tracklist length has a ceiling of 10,000 and the default is 10,000. Also added in the core config values to relevant test cases. I think that's everything mentioned in 997.
Any suggestions/concerns?
> Issue: #997 Add a track-list length limit.

- mopidy/mpd/translator.py
Fixes #1212
When stream_title is set:
use stream_title for mpd's Title field, and use track.name (if set) for mpd's Name field
When stream_title is not set:
use track.name for mpd's Title field. Do not output Name field.
> mpd:Fix swapped Name and Title fields for streams

- tests/m3u/test_playlists.py
Encoding is different on Mac OS and needs to be checked separately.
> tests: Fix failing encoding test

- mopidy/internal/path.py
- tests/__init__.py
- tests/core/test_history.py
- tests/internal/test_path.py
This fixes #1240.
In internals/path.py. there is a snippet of code that multiples mtime
for a file with 1000, and then casting it to `int`. This pseudo-casting
is pointless, as it only truncates to an integer (whole number), instead
of actuallly ensuring the type is an <int>.
>>> type(int(2**32))
<type 'long'>
Instead, fix the tests to look for (int, long).
This bug found on a 32-bit VM :)
> tests: fix test breakage due to promotion from int to long

- docs/changelog.rst
- mopidy/stream/actor.py
If Mopidy-File is enabled it handles playback of file:// URIs.
Mopidy-Stream used to do this, but in Mopidy 1.1 we removed "file" from
the default value of the stream/protocols config. However, many users
upgrading to Mopidy 1.1 have set stream/protocols to include "file" in
their existing config, and thus Mopidy fails to start because both
backends tries to claim the "file" protocol.
Fixes #1248
> stream: Ignore file protocol if Mopidy-File is enabled

- docs/changelog.rst
- mopidy/audio/scan.py
Seems I broke this back in match with 9e8b3263abf5fa8529dedeb46392f8f19eb723f4, could also be back-ported easily to 1.0.x as this was introduced for 1.0.0
> audio: Fix scan timeout handling

- docs/changelog.rst
- mopidy/audio/scan.py
- tests/audio/test_scan.py
- tests/data/scanner/plain.txt
- tests/data/scanner/playlist.m3u
Pre 1.1 we didn't notice this as we had built in support for MIMEs like text/uri-list, so at least we don't need to backport anything.
> audio: Make scanner report MIME for missing plugins

- docs/changelog.rst
- mopidy/local/ext.conf
@tkem recommends that this is reduced from 1000 to maximum 100 to not
block incoming requests to Mopidy-Local-SQLite for too long while
scanning the local library.
> local: Lower the default scan_flush_threshold

- mopidy/core/library.py
Resolves  issue #1198 by adding a list of available search fields to the documentation for search() in LibraryController.
> docs: Add available search terms to LibraryController search

- docs/changelog.rst
- mopidy/core/playback.py
- mopidy/core/tracklist.py
- tests/mpd/protocol/test_current_playlist.py
- tests/mpd/protocol/test_playback.py
- tests/mpd/protocol/test_status.py
- tests/mpd/test_status.py
The original MPD server starts at 1. upmpdcli has issues with Mopidy
starting at 0 instead, as 0 is special in its context.
As noone should care exactly what core's TLIDs are, I opted to start
counting both core TLID and MPD songid from 1, instead of just
increasing TLID with 1 in the MPD frontend to get a valid songid. This
also keeps it easier to debug across the MPD/core boundary.
> core, mpd: Start tlid/songid counting at 1

- mopidy/core/playback.py
- tests/core/test_playback.py
Trigger playback ended on:
- stream changed
- EOS
- stop via stream changed events
Old behavior was to manually trigger on:
- next
- prev
- play with other track and old state != STOPPED
- stop
> core: Cleanup track ended event handling

- mopidy/core/playback.py
- tests/core/test_playback.py
- tests/local/test_playback.py
- tests/local/test_tracklist.py
Some test cleanups and then just making sure we get state changed events. This should fix the case where MPD doesn't notice what we changed songs when doing `idle player`
> Core state change events between tracks

- docs/changelog.rst
- mopidy/core/actor.py
- mopidy/core/playback.py
- tests/core/test_playback.py
Fixes:  #312, #1304 (partially), #1305
Changelog to follow once I've reviewed the diff again.
> Gapless aware seek handling

- docs/changelog.rst
- mopidy/core/listener.py
- mopidy/listener.py
- mopidy/mpd/actor.py
- mopidy/mpd/dispatcher.py
- mopidy/mpd/session.py
- tests/mpd/protocol/test_idle.py
- tests/mpd/test_actor.py
This combined with #1346 provides a much nicer experience when seeking as clients are far less likely to end up out of sync.
> MPD idle cleanup

- tests/core/test_playback.py
So, it turns out this does not work the way I thought after all.
Although ``_mark_unplayable`` does not actually remove the tracks, ``core.PlaybackController.next()`` is eventually called for every track (even unplayable ones), which in turn invokes ``self.core.tracklist._mark_played(original_tl_track)``` to remove the track from the tracklist.
I've written a few test cases to prove the point, for the interested reader.
> Test cases for checking that unplayable tracks are consumed. 

- docs/clients/mpd.rst
- docs/ext/frontends.rst
- docs/ext/mixers.rst
- docs/ext/web.rst
Fixes a few typos I came across while going through the documentation.
The entry for Mopidy-Party was duplicated, so I've removed one of those as well.
> Fix documentation typos and inconsistencies.

- docs/contributing.rst
- docs/releasing.rst
Adds a note that describes the process for submitting a bug fix PR for an existing minor release of Mopidy.
Contains the proposed changes required for https://github.com/mopidy/mopidy/issues/1355.
I thought just adding a note at the bottom of the page was sufficient instead of starting a whole new section (as the process is so similar to submitting a PR for 'develop')?
> docs: Provide details on PR procedure for bug fix releases

- mopidy/zeroconf.py
Calls dbus dependent code only if dbus was actually imported. Also sets `display_hostname` and `name` before trying to call dbus-dependent code
> Address mopidy/mopidy#1335

- docs/api/core.rst
- docs/changelog.rst
- mopidy/core/playlists.py
- tests/core/test_playlists.py
Adds a new method `PlaylistsController.get_uri_schemes()` which mirrors `Core.get_uri_schemes()`, but only returns schemes for backends with a playlists provider.
This can be used by clients which want to pass the optional `uri_scheme` parameter to `PlaylistsController.create()`. Without this, clients will usually
- do not use the `uri_scheme` parameter at all, so playlists get created by the *first* backend that provides playlists (not always what's desired, and there need not be a playlist-aware backend installed)
- set `uri_scheme` to a hard-coded value, for example `m3u`, which may not even be available
- let the user choose from the URI schemes provided by `Core.get_uri_schemes()`, which reports backends that don't provide playlist support, too
See also …
> core: Add PlaylistsController.get_uri_schemes().

- docs/changelog.rst
- mopidy/m3u/translator.py
- tests/data/comment-ext.m3u
- tests/data/one-ext.m3u
- tests/data/two-ext.m3u
- tests/m3u/test_translator.py
Basically just @Joolee's patch for providing a sensible track name for non-extended M3Us; see #1364.
Other issues from #1364 will be addressed separately in #1370.
> m3u: Derive track name from file name for non-extended M3U playlists.

- tests/core/test_playback.py
Test to ensure that pause->next->resume handles unplayable tracks just like stop->next->play does (if I understand how the track handling and eventing works in the test framework correctly).
> test: Test case for skipping unplayable tracks when paused.

- docs/changelog.rst
- mopidy/core/playback.py
- tests/core/test_playback.py
Suggested fix for #1352 
Replaces https://github.com/mopidy/mopidy/pull/1353 which was created against the wrong branch (I'm an idiot).
> Mark track as playing and add to history if changing track while paused.

- mopidy/httpclient.py
- tests/test_httpclient.py
Logic and test case to handle situation where the ```port``` parameter is either missing from the configuration file entirely, or set to an empty string.
> Handle missing or empty 'port' configuration parameter.

- docs/changelog.rst
- mopidy/core/library.py
- tests/core/test_library.py
> core: Make lookup() ignore tracks without URI

- docs/changelog.rst
- mopidy/core/playback.py
- tests/core/test_playback.py
Proposed fixes for https://github.com/mopidy/mopidy/issues/1378.
This PR is based on https://github.com/mopidy/mopidy/pull/1356 as the changes overlap somewhat, so should probably be merged in that sequence.
The quick fix in ```PlaybackController._change_track``` is becoming little messy as it now includes hacks for three issues :( But a lot of this has changed in gapless so should be ok if there are no further changes?
> Skip over unplayable tracks when paused

- mopidy/core/playback.py
- tests/core/test_playback.py
> Fix track_playback_ended event in consume mode

- docs/ext/backends.rst
> Fix #1410: Link mopidy-local-{images,sqlite} to mopidy repo.

- docs/config.rst
If only reading the config page, you might not have realized that the
config is located in another place when running Mopidy as a service.
> docs: Add a note about running as a service under config

- docs/service.rst
When using PulseAudio and running Mopidy as a service, some
configuration has to be added for this. This documents what you have to
do.
This question comes up often enough on IRC that I figured we should document it. I wonder if the configuration is a bit verbose and detailed though, but I wanted to document it properly without any ambiguity.
The setup is based on these:
https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_over_network
https://github.com/mopidy/mopidy/issues/954#issuecomment-73369712
> docs: Add a note about PulseAudio when running as a service

- docs/changelog.rst
- mopidy/audio/actor.py
Sending the seek event to the playbin forwards it to all sinks. Which in turn
means on seek event per sink. To avoid this we inject the seek event in an
element before the tee.
> audio: Prevent double seeks in appsrc (fixes: #1404)

- mopidy/internal/gi.py
With gst-python >= 1.5.2, a NotInitialized exception is thrown if Gst.is_initialized is called before Gst.init. This removes the Gst.is_initialized check, as Gst.init should be a noop if run again after the first call. This also adds an argument to Gst.init as gst-python >= 1.5.2 requires that as well.
Additionally, after fixing that, I got some warnings when importing GstPbutils before calling Gst.init, so that import is moved below the init, which removed the warnings.
This fixes #1432.
> Fix errors and warnings when importing Gst with gst-python >= 1.5.2

- mopidy/__main__.py
- mopidy/commands.py
- mopidy/internal/process.py
This should fix #1435. I left the old SIGTERM handler in place for subcommands that don't run the GLib mainloop.
@dublok @trygveaa Does this fix the issue for you?
> Stop GLib mainloop on SIGTERM

- docs/changelog.rst
- mopidy/audio/actor.py
Fixes #1430. See #1222 for explanation and proper fix.
> audio: Workaround crash caused by race

- docs/changelog.rst
- docs/config.rst
- mopidy/audio/actor.py
- mopidy/config/__init__.py
- mopidy/config/default.conf
- tests/audio/test_actor.py
It may help to increase this for users that are experiencing buffering
before track changes. Workaround for #1409.
Not sure if I should have added any tests for this, and if so how?
> audio: Add a config option for queue buffer size

- docs/changelog.rst
- mopidy/audio/actor.py
- mopidy/audio/tags.py
Don't think this needs a changlog entry. The bad behavior this fixes was never released.
> Postpone tags between about-to-finish and stream-start

- docs/changelog.rst
- mopidy/stream/actor.py
- tests/stream/test_library.py
- tests/stream/test_playback.py
Probably replaces #1446. Main thing missing for 2.0 is a changelog, but it's time for bed now...
> Make sure the stream backend playback/library handle URIs the same way

- mopidy/local/translator.py
I found this mistake when reading the documentation of Mopidy. Just add
a "to"  to the annotation.
I just want the mopidy better.
> Modify a mistake in annotations

- docs/changelog.rst
- mopidy/mpd/protocol/playback.py
- tests/mpd/protocol/test_playback.py
I found an error in the implementation of the MPD protocol:
* with `mpd` 0.19.5:
```
$ telnet 127.0.0.1 6600
...
OK MPD 0.19.0
replay_gain_status
replay_gain_mode: off
OK
```
* with `mopidy` df0d534a56fd10682816b87f8f3145ee4c7162ac (current `develop` branch):
```
$ telnet 127.0.0.1 6600
...
OK MPD 0.19.0
replay_gain_status
off
OK
```
This led to the [following issue](https://github.com/kstep/rust-mpd/issues/5). This PR is a simple attempt at solving the issue (without implementing actual replay gain support).
> mpd: fix protocol for replay_gain_status

- mopidy/stream/actor.py
default timeout is converted from ms to seconds for http download and warning has correct number of arguments. Fix avoids blocking of mopidy while it is busy downloading whole stream for a unfortunately long period.
> fix/1521 download timeout sec 

- mopidy/models/__init__.py
the doc string was not consistent with the current type definition
> model documentation: update 'composers' and 'performers' type

- mopidy/core/playback.py
- tests/core/test_playback.py
@adamcik Is there a reason why you check for position match in `_on_position_changed`? It seems there is only one `_on_position_changed` for each `seek`. (I tried to, but didn't get two simultaneous seeks)
Fixes #1462.
> Ignore position of _on_position_changed callback. Fixes #1462

- docs/changelog.rst
- mopidy/core/playback.py
Playback callbacks now correctly handle the following cases:
1. the track finishes and switches to the next one in the list;
2. user presses next / previous
Fixes #1456 (and therefore should also close mopidy/mopidy-scrobbler#20).
> Get correct track position on change events

- docs/ext/backends.rst
Hello all,
quite a while ago the leftasrain.com maintainers have changed the way the serve song files (requiring a time-limited token to access the song every time). I guess it would still be possible (but more complicated) to implement in a Mopidy plugin, but I don't think that it's woth the effort, which leaves the [Mopidy-LeftAsRain](https://github.com/naglis/mopidy-leftasrain) plugin broken, so I think it would be best to remove the link from the documentation.
Thanks!
> docs: Remove link to the Mopidy-LeftAsRain plugin

- mopidy/local/commands.py
- Currently the code skips directories with level > 1 starting with .,
but does not skip first-level directories starting with .; fix this
by matching for files/directories which start with . in addition to
those that contain /.
> Do not scan first-level dirs starting with .

- docs/changelog.rst
- mopidy/audio/tags.py
- tests/audio/test_tags.py
Replacement for #1495
The `Models.Track.date` member has to be set correctly. mpd (and other code, see #1495) relies on it.
> Scanner: Set date to track and album: fix #1471

- docs/changelog.rst
- mopidy/audio/scan.py
We broke MMS playback since mmssrc can't go to playing async. This adds some logging I used for debugging, and will be using again. And more importantly gives up on getting the duration in switching to PLAYING isn't done async.
> Handle GStreamer source elements that can't go playing async

- docs/changelog.rst
- mopidy/audio/scan.py
This increases the robustness by quite a bit, we no longer:
- Fail on elements such as mmssrc that can't go to playing ASYNC.
- Try going to playing if we've already tried before.
> audio: Wait for state change instead of async done in scanner.

- docs/installation/raspberrypi.rst
As of Decemer 2016, SSH is disabled on default in Raspbian for security reasons. I've added a small note how to enable the SSH.
Sources:
https://www.raspberrypi.org/blog/a-security-update-for-raspbian-pixel/
https://raspberrypi.stackexchange.com/questions/1747/starting-ssh-automatically-at-boot-time
> Docs: instructions how to enable SSH on first boot

- docs/changelog.rst
- mopidy/mpd/protocol/status.py
- tests/mpd/protocol/test_reflection.py
-First bug fix so if there is any corrections or advice please let me know. Criticism is welcome as I am here to learn and help contribute best that I can.
> Changed Idle's list command to True. In order to stay in convention with MPD

- mopidy/internal/gi.py
This makes Mopidy properly show up in pulseaudio as "Mopidy" instead of
"python*"
> Set GLib prgname and application name

- mopidy/core/library.py
- tests/core/test_library.py
> Fix library.lookup with an empty uri list

- docs/ext/backends.rst
The Deezer extension has been removed from Github at Deezer's request, so is no longer available.
https://github/dmca/blob/master/2018/2018-01-12-Deezer.md
> Remove Deezer backend

- mopidy/file/library.py
Leaving the .encode in the code causes folders with non-ASCII symbols (tested with some German umlauts) to show up empty in "browse".
After removing, the folder contents show up fine.
(If this gets merged, I don't have to patch my kids' three mediaplayers for their "Hörspiele" (audiobooks) folder everytime a new Mopidy version gets installed. It's just daddy, trying to save some of his time... ;-) )
> remove leftover utf-8 encode from path handling

- docs/changelog.rst
- mopidy/config/__init__.py
- tests/config/test_defaults.py
This pull request remove the hard 10000 tracks limitation in playlists #1600
> config: remove 10000 tracks limitation in playlists

- docs/changelog.rst
- docs/ext/http.rst
- mopidy/http/__init__.py
- mopidy/http/ext.conf
- mopidy/http/handlers.py
- tests/http/test_handlers.py
- tests/http/test_server.py
A fix for some of https://github.com/mopidy/mopidy/issues/1659
> Protect RPC interface against CSRF

- docs/changelog.rst
- mopidy/mpd/protocol/stored_playlists.py
- tests/dummy_backend.py
- tests/mpd/protocol/test_stored_playlists.py
This is the fix for #1511 that I forgot to submit.
Tests currently fail due to https://github.com/mopidy/mopidy/issues/1619.
> Lookup track metadata for MPD load and listplaylistinfo

- docs/changelog.rst
- mopidy/backend.py
- mopidy/core/playlists.py
- mopidy/m3u/playlists.py
- mopidy/m3u/translator.py
- tests/core/test_playlists.py
- tests/m3u/test_playlists.py
This PR:
- Defines the return value of `core.playlists.delete()` to be a success bool.
- Updates the M3U backend to use `mopidy.internal.path.is_path_inside_base_dir()` to check if any received URI/path is inside the `m3u/playlist_dir` directory. If not, the request is treated as if the path doesn't exist.
This should plug the last part of #1659 and make us ready to release Mopidy 2.2.
> Fix arbitrary file access in M3U backend

- tests/core/test_playback.py
Towards https://github.com/mopidy/mopidy/issues/1694.
Use this is a base for reproducing the tables at https://docs.mopidy.com/en/latest/modules/mpd/#mopidy.mpd.protocol.playback.next_ and https://docs.mopidy.com/en/latest/modules/mpd/#mopidy.mpd.protocol.playback.previous and
> Better next and previous track tests

- docs/changelog.rst
- mopidy/http/handlers.py
- tests/http/test_handlers.py
check_origin() still ensures the Origin header is set but now only blocks
when missing from the allowed list *if* a network location was extracted
from the header. This prevents websocket connections originating from
local files (common in Apache Cordova apps such as Mopidy-Mobile) from
being blocked; these files don't really have a sensible value for Origin
so the client browser sets the header to something like 'file://' or
'null'.
Also added some tests for check_origin().
> http: allow local files to access websocket (Fixes #1711)

- docs/changelog.rst
- docs/ext/http.rst
- mopidy/http/__init__.py
- mopidy/http/ext.conf
- mopidy/http/handlers.py
- tests/http/test_handlers.py
- tests/http/test_server.py
This will remove the requirement to set a ``Content-Type: application/json``
header for JSON-RPC POST requests. It will also disable all same-origin
checks, effectively ignoring the ``allowed_origins`` config since requests
from any origin will be allowed. Lastly, all ``'Access-Control-Allow-*``
response headers will be suppressed.
I am not sold on the config name but I wanted to make it really clear that setting it is less secure. Alternate name suggestions welcome.
Also, I am not 100% sure if we should be disabling all the protections (as is currently implemented here) or if we should just remove the requirement to set a `Content-Type` header...
> http: Add config option to disable CSRF protection (Fixes: #1713)

- docs/changelog.rst
- mopidy/http/actor.py
From Tornado v5.0:
> IOLoop.instance is now a deprecated alias for IOLoop.current. Applications that need the cross-thread communication behavior facilitated by IOLoop.instance should use their own global variable instead.
We were using IOLoop.instance to stop the HTTP server thread from a different thread.
> http: use current Tornado IOLoop when stopping. (Fixes #1715).

- docs/config.rst
- mopidy/config/types.py
- tests/config/test_types.py
I don't know if we want to expose our internal custom log level but I have found this very useful recently.
> Specifying 'trace' level logging through the loglevels config

- mopidy/file/ext.conf
- mopidy/local/ext.conf
Hi - my local music collection is littered with PDF and Zip and it seems to me there's no reason not to exclude them, right? JPEGs are excluded by default (e.g. cover art) and actually that's the same reason why I have PDFs - "liner notes" etc. I hope this proposed pull is appropriate. Thanks for your work.
> local, file: exclude .pdf and .zip in default config

- mopidy/internal/playlists.py
- tests/config/test_config.py
- tests/core/test_playback.py
- tests/internal/test_path.py
- tests/local/test_json.py
Ignore N813 when importing the c version of xml.etree.ElementTree.
Ignore N815 when controlling failure diff length in unittest.
> test: flake8 to ignore camelcase usage in our deps.

- docs/changelog.rst
- mopidy/audio/actor.py
The 'always connected fakesink' is causing problems when switching
between tracks with different sample rates and with some custom
output pipelines. Since it's only there to support dynamic outputs,
which we don't yet support, we might as well remove it for now.
> audio: removed unused fakesink. (Fixes #1528)

- tests/audio/test_scan.py
The file order returned by .find is not deterministic which made
testing the first scanner result fail when it happened to be an unsupported
media format (e.g. mp3).
> test: Skips scanner tags test when there's no mp3 support.

- docs/changelog.rst
- mopidy/audio/actor.py
Successor to #1734 which retains our GST `BUFFERING` message handling but prevents it from erroneously setting the pipeline state `PLAYING`/`PAUSED` when we want to stay in `READY` (during track changes).
> Disable buffering handling during track change. (Fixes #1722)

- .travis.yml
- tests/audio/test_scan.py
Can remove all the `check_if_missing_plugin()` calls if we are aiming to always have mp3 support. 
Probably need to force a few Travis runs to make sure this actually worked.
> Include Gstreamer mp3 plugins in Travis environment.

- docs/api/core.rst
- docs/changelog.rst
- mopidy/core/actor.py
- mopidy/core/playback.py
- mopidy/core/playlists.py
- mopidy/core/tracklist.py
- mopidy/internal/deprecation.py
- setup.cfg
- tests/core/test_actor.py
- tests/core/test_playback.py
- tests/core/test_tracklist.py
- tests/local/test_playback.py
- tests/local/test_tracklist.py
- tests/mpd/protocol/test_current_playlist.py
- tests/mpd/protocol/test_music_db.py
- tests/mpd/protocol/test_playback.py
- tests/mpd/protocol/test_regression.py
- tests/mpd/protocol/test_stored_playlists.py
- tests/mpd/test_status.py
This removes all the properties in the Core API that have been deprecated since 1.0.
This is a large part of #1083 and #1461, but does not completely resolve those.
> Core API: Remove deprecated properties

- docs/api/core.rst
- docs/changelog.rst
- mopidy/core/library.py
- mopidy/core/playback.py
- mopidy/core/playlists.py
- mopidy/internal/deprecation.py
- tests/core/test_library.py
- tests/core/test_playlists.py
- tests/internal/test_jsonrpc.py
- tests/m3u/test_playlists.py
This removes all methods in the Core API that was deprecated in 1.0.
As the previous PR, this contributes to #1461 without resolving it fully.
> Core API: Remove deprecated methods

- docs/changelog.rst
- mopidy/core/library.py
- mopidy/core/tracklist.py
- mopidy/internal/deprecation.py
- mopidy/mpd/protocol/current_playlist.py
- mopidy/mpd/protocol/music_db.py
- tests/core/test_library.py
- tests/core/test_tracklist.py
- tests/internal/test_jsonrpc.py
- tests/local/test_playback.py
- tests/local/test_tracklist.py
- tests/mpd/protocol/test_current_playlist.py
- tests/mpd/protocol/test_music_db.py
This removes all deprecated arguments in the Core API, with the exception of `tracklist.add(tracks=...)`. However, this PR includes a couple of improvements to make it easier to remove `tracklist.add(tracks=...)`.
This almost completes #1461.
> Core API: Remove deprecated args

- mopidy/internal/playlists.py
- tests/internal/test_playlists.py
`File#` entries of PLS playlists may be found double quoted in the wild, since the "standard" is loosely defined. The resulting URI is then incorrect and makes mopidy fail to load the content, so let's make sure we strip them.
Fixes #1770
> Remove double-quotes around PLS File# entries

- docs/changelog.rst
- mopidy/internal/network.py
- tests/internal/network/test_lineprotocol.py
This goes towards fixing #1762. Needs some tests and changelog etc.
> Close MPD connection following an exception in handler.

- mopidy/ext.py
- tests/test_ext.py
sry for creating a new PR. I'm only a little server admin and rebasing was too scary :wink:.
I changed the base branch to `release-2.2` and started again. 
> Lovely to find a PR with a fix just hours after I created the issue! :-)
> 
> A couple of comments:
> 
> According to this [setuptools commit](https://github.com/pypa/setuptools/commit/92a553d3adeb431cdf92b136ac9ccc3f2ef98bf1) the new methods where added in setuptools 11.3 about five years ago. According to [packages.debian.org](https://packages.debian.org/search?keywords=python-setuptools), Debian oldstable (stretch) ships setuptools 33. In other words, we can safely remove the `if hasattr(...)` and instead assume the "new" API to be present.
> 
> Second, some tests in `tests/test_ext.py` are failing. It seems you simply need to …
> fix: PkgResourcesDeprecationWarning from mopidy/ext.py

- docs/changelog.rst
- docs/command.rst
- docs/config.rst
- docs/troubleshooting.rst
- mopidy/__main__.py
- mopidy/commands.py
- mopidy/config/__init__.py
- mopidy/config/default.conf
- mopidy/internal/log.py
- tests/test_help.py
See #1452 for background and reasoning.
> Simplify logging

- docs/changelog.rst
- mopidy/internal/network.py
- mopidy/mpd/actor.py
- mopidy/mpd/session.py
- tests/internal/network/test_connection.py
- tests/internal/network/test_server.py
- tests/internal/network/test_utils.py
- tests/mpd/test_session.py
This, along with some formatting, was broken in #1629.
Also added some mpd.session tests for the log messages.
> network: log client address not server address. (Fixes #1788)

- mopidy/file/library.py
- tests/file/test_lookup.py
The `copy` method of our models has been deprecated for some time and was finally removed as part of #1774
Also added a simple test.
> FileBackend using Track.replace() instead of Track.copy()

- mopidy/core/actor.py
- tests/core/test_actor.py
This was missed during #1768. Partly because it has no test coverage, so I added something simple.
> state_changed should use getter/setter for accessing playback state.

- tests/stream/test_playback.py
Spotted this during #1802. I guess it was a copy and paste error somewhere along the way.
> fix stream tests to assert that all log strings are in caplog.text

- docs/changelog.rst
- mopidy/core/actor.py
- tests/core/test_playback.py
I've been using this change quite happily and seems worth it until we have proper stream type support.
> emit stream_title_changed when title differs from track name

- docs/changelog.rst
- mopidy/compat.py
- mopidy/stream/actor.py
- tests/stream/test_playback.py
This doesn't actually fix the example given in #1785 since it's a HLS stream and our stream backend will only play the first segment. We should fix HLS support separately.
> handle stream playlists containing relative URIs

- docs/changelog.rst
- mopidy/mpd/protocol/stored_playlists.py
- mopidy/mpd/translator.py
- tests/mpd/protocol/test_status.py
- tests/mpd/test_translator.py
I missed Album URIs in #1805. And a changelog entry.
> More fixes for non-ASCII chars in MPD uris

- mopidy/audio/utils.py
- mopidy/stream/actor.py
- tox.ini
I'm not sure I did the right thing here.
`http.download()` gives us bytes, which is what `playlists.parse()` wants and also returns to us. And I've decoded that assuming utf-8 to match what `uris` is. But surely it's much better for `http.download()` to decode the bytes using the actual server encoding and then if `playlists.parse()` really wants to do deal in bytes (must it?) then we encode/decode around that.
> py3: Stream backend

- mopidy/compat.py
- mopidy/mpd/protocol/__init__.py
Use `compat.getargspec` elsewhere [as suggested in #1813](https://github.com/mopidy/mopidy/pull/1813#discussion_r332295364). However, this does lose Python3's check for `kwonlyargs` so maybe this fix isn't as good as what we already had. 
Defined `compat.getcallargs` since that has also been deprecated in Py3. Note: the MPD tests currently don't work so this is untested. Happy to wait for those to be fixed before merging this.
> Py3: More deprecated inspect functions

- docs/installation/debian.rst
I've pretty much restored what we used to have when supporting both jessie and stretch.
> Use Debian stretch packages for Ubuntu 18.04

- docs/changelog.rst
- mopidy/ext.py
- tests/test_ext.py
- tox.ini
I opted to change the external API towards the extensions for the better. I think spreading pathlib to them is more helpful than requiring them to discover all the subleties of path handling themselves.
> py3: Convert mopidy.ext

- mopidy/mpd/protocol/music_db.py
- tests/mpd/protocol/test_current_playlist.py
- tests/mpd/protocol/test_playback.py
- tests/mpd/protocol/test_regression.py
- tests/mpd/protocol/test_stored_playlists.py
- tox.ini
Continue returning integer playtime value.
Fix test to handle different random number generation between versions.
Broken test was comparing 'ThreadingFuture' and 'int'.
> Py3: Convert remaining parts of mopidy.mpd.protocol

- docs/changelog.rst
- docs/installation/source.rst
- mopidy/internal/gi.py
This is available in:
- [Debian stable (buster) and newer](https://packages.debian.org/search?keywords=gstreamer1.0-plugins-base)
- [Ubuntu 18.04 (LTS) and newer](https://packages.ubuntu.com/search?keywords=gstreamer1.0-plugins-base)
Fixes #1739
> deps: Require GStreamer >= 1.14.0

- mopidy/__main__.py
- mopidy/config/__init__.py
`surrogateescape` error handling should give us enough support to support arbitrary file paths in the config file.
> config: Handle config files as text

- mopidy/audio/actor.py
Py2 used bytes, changed to str.
> audio: set appsrc source properties using strings.

- docs/changelog.rst
- mopidy/internal/deps.py
- tests/internal/test_deps.py
On one example setup, this reduces the output of `mopidy deps` from 499 to 137 lines. No data is lost, we just don't repeat the ~8 lines of dependencies of Mopidy itself for every extension that also depends on Mopidy.
> deps: Don't repeat Mopidy's deps for each extension

- mopidy/commands.py
- tests/test_commands.py
> Stop using bytes when parsing command line --options string

- mopidy/audio/actor.py
On Python 2, we used `str(error)` to get a native string representation, aka bytes, and then used `.decode()` on that to get a Unicode string.
On Python 3, the `str(error)` call returns Unicode, which doesn't have a `.decode()` method, so the error/warning handler crashes.
I added `ipdb` tracing, provoked an error, and investigated the objects we get from GStreamer:
- `error` is a `GLib.GError` which has a good `str()`/`repr()`, as well as `.message`, `.domain`, and `.code` attributes.
- `debug` is a string
There were no traces of bytes that needed decoding in the objects.
Fixes #1851
> audio: Fix logging of GStreamer warning/error

- docs/changelog.rst
- mopidy/core/playback.py
- mopidy/core/tracklist.py
- setup.cfg
This PR builds upon #1786 by @hugovk, and takes the easy way out: We postpone the replacement of our usage of the deprecated APIs until after Mopidy 3.0 has been released. The important thing is to deprecate them, so that they can be removed in the next major, not to immediately stop using them ourselves.
> Promote APIs from "pending deprecation" to "deprecated"

- mopidy/commands.py
I think this came in with the latest flake8-bugbear.
In related news, the following command from [our docs](https://docs.mopidy.com/en/latest/devenv/#install-development-tools) doesn't *update* the development dependencies like I assumed it would:
```
(mopidy3) nick@xps:~/Dev/mopidy-dev/mopidy$ pip install --upgrade --editable ".[dev]"
Obtaining file:///home/nick/Dev/mopidy-dev/mopidy
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: tornado>=4.4 in /home/nick/.virtualenvs/mopidy3/lib/python3.7/site-packages (from Mopidy==3.0.1) (6.0.3)
Requirement already satisfied, skipping upgrade: Pykka>=2.0.1 in /home/nick/.virtualenvs/mopidy3/lib/python3.7/site-packages (from …
```
> flake8: Moved return outside of finally block

- docs/changelog.rst
- mopidy/core/actor.py
- tests/core/test_playback.py
Fixes #1871
PR #1751 introduced a regression where, following a normal gapless
track change, the stream_title was incorrectly set to the previous
track's title.
This still isn't very good as we are still emitting the bogus `stream_title_changed` event for the previous track's title. That is because we keep any tags we get after `about_to_finish` fires in `pending_tags`, and then emit them when the track change completes (`on_stream_start` fires), even if they were old tags for the previous track.
> core: Reset stream title after all ``title`` tag changes.

- mopidy/config/keyring.py
Hello,
Current keyring configuration source doesn't really work - it fails with `TypeError: string argument without an encoding` whenever there is something mopidy-related in the keyring.
`dbus` package returns strings as [`dbus.String`](https://dbus.freedesktop.org/doc/dbus-python/dbus.html#dbus.String) types that can't be byte-encoded without passing `encoding` explicitly. Moreover, the rest of the code doesn't really expect bytes there - [it wants strings](https://github.com/mopidy/mopidy/blob/develop/mopidy/config/keyring.py#L63) (otherwise it will not find the key in dictionary, since `b'section' != 'section'`). This PR converts the DBus attribute name/value pairs to `string`s explicitly and therefore fixes the `TypeError: string argument without an encoding` error.
> Convert `dbus.String` into python strings when importing config from keyring

- mopidy/config/__init__.py
Closes #1878 
I added an `unknownsection` to my config and an `unknownvalue` to `scrobbler` to see how it looks. Turns out I already config set for 2 extensions that I don't have installed.
```
INFO     2020-03-17 23:08:11,518 [1:MainThread] mopidy.config
Loading config from command line options
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
Ignoring config section 'local': A matching extension was not found
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
Ignoring config section 'soundcloud': A matching extension was not found
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
Ignoring config section 'unknownsection': A matching extension was not found
INFO     2020-03-17 23:08:12,261 [1:MainThread] mopidy.__main__
Enabled extensions: gmusic, …
```
> Increase logging level for invalid config

- docs/installation/index.rst
makes the new fedora installation instructions visible under installation/. follow-up for #1881.
> include fedora.rst in installation toctree

- docs/changelog.rst
- mopidy/backend.py
- tests/core/test_playback.py
Related to #1888
The decision to use "download" buffering may depend on the uri, similar to `is_live`.
e.g. some backends that can provide very long tracks might not want to use this buffering strategy for those tracks. 
Also added a changelog entry for #1888
> backend: should_download takes a uri parameter.

- mopidy/config/__init__.py
Latest flake8 catches this. Probably should be cherry-picked to master also?
> config: fix missing file path in warning message.

- setup.cfg
We somehow lost this during our 2to3 transition.
> Added tox to dev requirements. (Fixes #1908)

- docs/changelog.rst
- mopidy/audio/tags.py
Embedded cover art, and other tags exposed to us as type `Gst.Sample`, were
causing memory leaks when converted to plain Python types using
`GstBuffer.extract_dup()`. `extract_dup()` expects the caller to free the
memory it allocates but older versions of the python3-gi don't seem to do
this. The workaround is to access samples using `GstMemory` methods instead.
This issue was present on Buster 10 systems (python-gi 3.30.4) but not on
Ubuntu 20.04 (python-gi 3.36.0).
Fixes #1827
[Zulip Topic](https://mopidy.zulipchat.com/#narrow/stream/207265-mopidy-dev/topic/Memory.20Leaks)
> Fix memory leak when converting GST `sample` tags

- mopidy/file/library.py
- tests/file/test_browse.py
Fixes #1906 
Added log error message to gracefully handle exception when trying to browse a path which is not a directory
> File: Gracefully handle error when browsing file

- .circleci/config.yml
- docs/codestyle.rst
- mopidy/internal/playlists.py
- mopidy/internal/process.py
- pyproject.toml
- setup.cfg
- tests/http/test_server.py
- tox.ini
Fixes #1919 
I'm starting this PR with adding CI for isort, which is already installed in the lint environment and already has some configuration in the repository.
Made the line length 80 to match the black setting.
Once it is confirmed that the CI works as expected, i.e. fails, I will push the next commit with the isort changes.
> Add isort to code formatting and CI

- .circleci/config.yml
- docs/changelog.rst
- setup.cfg
- tox.ini
This updates our test and CI setup to also run the test suite on Python 3.9.
> Support Python 3.9

- tests/internal/test_jsonrpc.py
reported via https://bugzilla.redhat.com/show_bug.cgi?id=1903954
```
tests/internal/test_jsonrpc.py .......................F................                                       [100%]
===================================================== FAILURES ======================================================
___________________ JsonRpcSingleCommandErrorTest.test_invalid_params_causes_invalid_params_error ___________________
self = <tests.internal.test_jsonrpc.JsonRpcSingleCommandErrorTest testMethod=test_invalid_params_causes_invalid_params_error>
def test_invalid_params_causes_invalid_params_error(self):
request = {
"jsonrpc": "2.0",
"method": "core.get_uri_schemes",
"params": ["bogus"],
"id": 1,
}
response = self.jrw.handle_data(request)
error = response["error"]
assert error["code"] == …
```
> fix test failure on python 3.10a2

- docs/releasing.rst
A couple of weeks ago, I discussed with @kingosticks and @adamcik how we could democratize the release procedure for extensions for me to no longer be the bottleneck for making releases.
The release procedure documented here is now in use for:
- mopidy-mpd
- mopidy-pandora
- mopidy-orfradio
- mopidy-spotify
This makes it possible for anyone with commit access to create releases to PyPI.
> New release procedure for extensions

- mopidy/audio/actor.py
- mopidy/audio/tags.py
- tests/audio/test_tags.py
These really clutter the debug log output and I am yet to find a case where it was interesting. Couldn't think of a better name for this function, open to suggestions!
> audio: log first few bytes only of tag value changes.

- docs/releasing.rst
Adjust the wording to match what is shown on PyPI.
> docs: make PyPI setup steps truely foolproof

- .github/workflows/release.yml
- docs/releasing.rst
As a followup to #1943, this automates parts of the release process for Mopidy itself.
> Automate parts of the release process

- extra/systemd/mopidy.service
This small change to the systemd service file will make mopidy wait for [`network-online.target`](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/).
The current behavior of this service is to only wait for `network.target`, which is specified in the standard to not wait for the internet to actually be up, only for the network interface to be functioning. This current behavior is unideal for users of extensions such as mopidy-spotify, where a functioning internet connection is expected and required at the time of startup.
This change will allow any mopidy extensions that require an internet connection to function properly on system startup, without needing to be manually reloaded after logging in. The impact to startup time should be trivial, a properly configured network …
> Make systemd service wait for internet connection

- mopidy/audio/tags.py
Without this with gst-python-1.18.2 while scanning files there are intermittent fails as follows:
```
ERROR    2020-12-18 18:39:25,302 [426578:Core-8] mopidy.core.library
FileBackend backend caused an exception.
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 17, in _backend_error_handling
yield
File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 217, in lookup
result = future.get()
File "/usr/lib/python3.9/site-packages/pykka/_threading.py", line 45, in get
_compat.reraise(*self._data['exc_info'])
File "/usr/lib/python3.9/site-packages/pykka/_compat/__init__.py", line 29, in reraise
raise value
File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 193, in _actor_loop
response = …
```
> Adjust to API change in gst-python >= 1.18

- docs/devenv.rst
There is a small typo in docs/devenv.rst.
Should read `possibility` rather than `possiblity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, possiblity -> possibility

- .github/workflows/ci.yml
- setup.cfg
The explicit dependency seems to break ReadTheDocs' building of the API
documentation. This reverts us back to only installing it for CI builds.
> Remove pyobject as explicit dependency

- .github/workflows/ubuntu-devel.yml
This PR adds a new GitHub Action independent of the CI setup that runs once every week, or when manually started from the GitHub Acitons UI.
Instead of using a custom Docker container as the CI build, which we must maintain, it uses the upstream `ubuntu:devel` container plus installation of Debian packages on each build. The benefit is that it will always use the latest version of the container, which is update now and then during the development of a new Ubuntu version, hopefully informing us of breaking GStreamer changes in time for us to fix it before the Ubuntu release. The drawback is that this build will be a bit slower than the regular CI build. However, that doesn't matter much as the build doesn't keep humans waiting for a green build on their PRs.
> Weekly build on next Ubuntu version

- mopidy/internal/log.py
The previous name of this method overrode a method with the same name in
the parent class that was related to lock acquisition. This was being
called internally by python logging code. Instead of releasing the lock,
this will have been accidentally dumping logs gathered before they were
ready to be handled. From what I can tell, this was happening just
before we manually called release(). This would give the appearance that
these logs were not being captured when in fact they were.
This fixes #1958
> Change name of "release" method in delayed logs handler

- docs/api/core.rst
I noticed this method was missing by chance while working on the API
explorer.
> Add missing playback controller method to API docs

- docs/api/http-server.rst
- docs/conf.py
- docs/contributing.rst
- docs/devenv.rst
- docs/extensiondev.rst
- Update some URLs to use HTTPS, or to follow redirects
- Account for the switch from setup.py to setup.cfg
- Update notes about installing graphviz to account for the fact that
pygraphviz is now a docs dependency defined in setup.cfg
> General documentation maintenance

- .github/workflows/ci.yml
- MANIFEST.in
- mopidy/backend.py
- mopidy/commands.py
- mopidy/ext.py
- mopidy/http/actor.py
- mopidy/http/handlers.py
- mopidy/internal/log.py
- mopidy/internal/network.py
- mopidy/mixer.py
- setup.cfg
- tests/config/test_config.py
- tests/test_ext.py
- tox.ini
This adds a mypy lint task in tox and CI and adds typing to a number of modules.
One use-before-definition bug in an exception handler has already been caught thanks to mypy. Bonus points for finding it in the diff ;-)
Modules that have type annotations are, until we're fully typed, explicitly added to `setup.cfg`. This way, we can gradually type more and more of Mopidy, similarly to how we gradually made more and more of the test suite pass on Python 3 in late 2019.
I've made extensive use of `from __future__ import annotations` in combination with keeping typing-only imports inside `if TYPE_CHECKING`. This ensures that the runtime performance hit from the type annotations is minimal.
> Initial type annotations and mypy setup

- mopidy/internal/log.py
- setup.cfg
This fixes the mypy part of the build. @jodal are these extra deps the correct way to do this or should we do something like this:
```
mypy --install-types --non-interactive
```
as mentioned at https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> typing: added missing library stubs and fixed logging DelayedHandler

- mopidy/exceptions.py
These cannot be renamed without breaking backwards compatability.
> Ignore N818 flake8 lint on existing exception classes

- mopidy/http/handlers.py
If clients are added/removed while a message is broadcast, a python error is raised: 
```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
response = self._handle_receive(envelope.message)
File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
return callee(*message.args, **message.kwargs)
File "/usr/lib/python3/dist-packages/mopidy/http/actor.py", line 82, in on_event
on_event(name, self.server.io_loop, **data)
File "/usr/lib/python3/dist-packages/mopidy/http/actor.py", line 89, in on_event
handlers.WebSocketHandler.broadcast(message, io_loop)
File "/usr/lib/python3/dist-packages/mopidy/http/handlers.py", line 112, in broadcast
for client in cls.clients:
RuntimeError: Set changed size during …
```
> Iterate over copy of websocket clients

- mopidy/http/handlers.py
Previously the check would reject requests with a Content-Type header
that looked like the following:
Content-Type: application/json; charset=utf-8
Now we handle this situation correctly.
> Improve CSRF protection Content-Type check

- mopidy/core/actor.py
- tests/core/test_actor.py
Previously when preparing sub-lists of backends (based on what they
support), we would still try to add the relevant backend to each list
even if an exception was thrown while fetching the relevant information.
This was problematic:
- If the very first backend encountered an issue, this code would also
throw an exception because some variables would be undefined
- If any other backends encountered an issue, this code would make
decisions based on the data obtained from a previous backend
Now we don't try to proceed with adding a backend to any sub-list if an
error occurs.
Also, the code used to construct the relevant error message in this
situation now uses an existing function to get the relevant backend's
classname.
> Resolve issue with backend lists preparation

- tests/internal/test_xdg.py
- tests/stream/test_playback.py
- tests/test_ext.py
@pytest.yield_fixture has been deprecated, as @pytest.fixture supports
generators just fine.
> Fix deprecation warning in pytest

- .readthedocs.yml
- The python version field is specified as a string in the docs
- Change 'htmldir' to 'dirhtml' as per the sphinx compatibility note in
the docs
> Updates to ReadTheDocs config

- mopidy/exceptions.py
> Ignore N818 flake8 lint on existing exception classes (#1988)

- mopidy/internal/log.py
Fixes Incompatible return value type (got "Optional[Any]", expected "bool")
> log: fix typing CI failure

- docs/changelog.rst
- mopidy/http/handlers.py
- tests/http/test_handlers.py
- tests/http/test_server.py
Fixes #2028.
Add CORS headers to RPC response.
This fixes a CORS error on chrome.
See #2028 for more information.
> Fix missing CORS headers on RPC response.

- docs/changelog.rst
- mopidy/config/__init__.py
- mopidy/config/types.py
- tests/config/test_types.py
- Added new Float type. It's very similar to the existing Integer type,
but accepts floating point numbers, and doesn't allow you to set
choices.
- Added new Pair type, for when you want to accept a pair of values in a
single config setting. Pairs default to a pair of strings, but you can
set either subtype to whatever type you want (including nested pairs).
- Added transformer property to String type. This allows you to apply an
arbitrary transformation to individual config settings that could
utimately be anything at all.
- If a transformation is applied to a String config value, it will now
return a subclass of the built-in str type. This subclass stores the
original value as well as the transformed value, so that it can be
re-serialised correctly.
- The "Expected Path" type originally …
> Add new config types, improve existing types

- mopidy/config/keyring.py
I'e been getting a strange error on Kubuntu 22.04. I can run Mopidy as a service, and I can run it from a .desktop file in ~/.config/autostart. But when I try to run it once logged in (ie from a terminal) I get
```
Traceback (most recent call last):
File "/home/bob/.virtualenvs/mopidy/bin/mopidy", line 33, in <module>
sys.exit(load_entry_point('Mopidy', 'console_scripts', 'mopidy')())
File "/home/bob/github/mopidy-dev/mopidy/mopidy/__main__.py", line 55, in main
config, config_errors = config_lib.load(
File "/home/bob/github/mopidy-dev/mopidy/mopidy/config/__init__.py", line 111, in load
raw_config = _load(files, defaults, keyring.fetch() + (overrides or []))
File "/home/bob/github/mopidy-dev/mopidy/mopidy/config/keyring.py", line 44, in fetch
session = service.OpenSession("plain", …
```
> Fix dbus exception where algorithm 'plain' is not supported

- mopidy/file/library.py
file exclusion not working for capital letter extensions as config is changed to lower(), but suffix is not changed if capital letters
> Update library.py suffix => suffix.lower()

- mopidy/http/__init__.py
- mopidy/http/handlers.py
- tests/http/test_handlers.py
- tests/http/test_server.py
This moves all of the processing for the `allowed_origins` HTTP setting into the config system, allowing it to be more easily reused by other extensions. It takes advantage of some new functionality in the `List` and `String` config types.
> Improve handling of "allowed_origins" HTTP config

- docs/changelog.rst
- mopidy/http/__init__.py
- tests/http/test_extension.py
> http: Fixed optional allowed_origins config setting.

- .github/workflows/ci.yml
- docs/changelog.rst
- docs/devenv.rst
- docs/installation/pypi.rst
- mopidy/__init__.py
- mopidy/backend.py
- mopidy/config/types.py
- mopidy/ext.py
- mopidy/http/actor.py
- mopidy/http/handlers.py
- mopidy/internal/log.py
- mopidy/mixer.py
- pyproject.toml
- setup.cfg
- tests/http/test_server.py
- tests/test_version.py
- tox.ini
Python 3.7 reaches end-of-life in a couple of months. The question then is what
minimum Python version we should support now.
We usually look to Debian stable and Ubuntu LTS when deciding what versions to
require of our dependencies:
- The 1y7m old Debian stable (Bullseye) includes Python 3.9.
- The 1y old Ubuntu LTS includes Python 3.10.
- The next Debian stable includes Python 3.11.
With this background, and the fact that Python 3.9 is already 2y5m old, it
seems very reasonable to skip Python 3.8 and increase our minimum supported
Python version to 3.9.
> Require Python >= 3.9

- docs/changelog.rst
- docs/installation/pypi.rst
- mopidy/internal/gi.py
With the same reasoning as in #2075, we should be able to increase the minimum
supported GStreamer version too:
- Debian 11 has GStreamer 1.18
- Ubuntu 22.04 LTS has GStreamer 1.20
- Ubuntu 23.04 will have GStreamer 1.22 next month
- Debian 12 will have GStreamer 1.22 this year
Thus, we can move to GStreamer 1.18 now and maybe 1.22 later this year.
> Require GStreamer >= 1.18

- docs/installation/debian.rst
As per https://wiki.debian.org/DebianRepository/UseThirdParty
Fixes #2069
> docs: Use Debian default keyring path.

- mopidy/file/library.py
While testing Mopidy-File.browse() it turned out that follow_symlinks=false do not work !
Current test is:
```
if child_path.is_symlink() and not self._follow_symlinks:
logger.debug("Ignoring symlink: %s", uri)
continue
```
but child_path is made with .resolve(), therefore symlinks are resolved, and follow_symlinks=false fails.
Changed to use dir_entry instead, which contains the unresolved entry (symlink etc.)
> Correct file/follow_symlinks error.

- tests/internal/test_path.py
- tests/m3u/test_playlists.py
- tests/test_ext.py
MacOS is a little bit different than Linux basically it puts "/private" in front of a number of standard paths.
I added conftest.py for now just with 2 tests IS_DARWIN and IS_WINDOWS, but I believe there are more common items between the test files, that could later go into conftest.py
I changed a few test in a way that the difference in path is very clear, which I prefer because "you see what you get" :-) but if there is a preference for a central function I can easily make that.
I am (currently) not trying to make mopidy work on MacOS, that would take a lot more testing, I just want a clean environment so that I can test locally before submitting my bug fixes.
> Allow tests to run on MacOS.

- docs/devenv.rst
- docs/extensiondev.rst
solve #2097 
If python 3.7 and 3.8 no longer are supported, the documentation should not reference it.
> docs: remove references to python 3.7.

- tests/file/test_browse.py
Running "tox -e flake8" on Mac flagged this error.
> tox -e flake8 failure solved.

- .github/codecov.yml
There are a number of false positives, where codecov claims the coverage have fallen 0,1% even though the code in reality have not been changed.
Adding codecov.yml allows to the threshold (and a world of other parameters) which the codecov action will then transmit.
This PR is tested on #2102, which turned green with this PR.
> Set codecov threshold to 0.3% before failing.

- docs/changelog.rst
- tox.ini
This allows to run a limited CI locally before pushing a PR.
It is limited in the sense that:
- all steps run with the installed python
- CodeQL is not run
- Coverage is not run
- "tox -e docs" is not run
It runs:
- pytest
- check-manifest
- flake8
- mypy
which covers programming errors.
Update changelog.rst to reflect this new possibility (not sure if that is correct).
> add "tox -e ci", to test before pushing.

- .gitignore
- docs/changelog.rst
- tox.ini
We have now activated pyright (even though I miss pyrightconfig.json), so "tox -e ci" should also be updated.
> tox CI now uses pyright.

- mopidy/ext.py
- tests/internal/test_deps.py
- tests/test_ext.py
I found a couple of smaller problems in dept.py and ext.py, and of course in order to test it 100% test coverage was added.
Basically added a number of hasattr() to ensure extensions have added attributes.
This is a part of a bigger change to get rid of pkg_resources, which is out_dated and are causing problems for me. But before I remove something I like to have 100% coverage of the existing version, making it easier to see changes.
> deps.py and ext.py 100% coverage.

- docs/changelog.rst
- mopidy/__init__.py
- mopidy/ext.py
- mopidy/internal/deps.py
- setup.cfg
- tests/internal/test_deps.py
- tests/test_ext.py
Pkg_resources is deprecated (see https://setuptools.pypa.io/en/latest/pkg_resources.html ) and produces a lot of warnings.
On a system with a lot of python packages pkg_resources is notoriously slow and memory hungry.
The changes to the production system is isolated in ext.py and internal/deps.py, care have been made to ensure the external interface and information are similar (not totally identical) and the 100% test coverage helps secure that.
importlib.metadata have one big difference to pkg_resources, it do not care about package versions, this seems to be a positive decision by pypa.
Because we support python v3.9 there is a need to import the compatibility lib (importlib_metadata). From python v3.10 this is no longer needed.
> Replace pkg_resources with importlib.metadata / import_module.

- mopidy/ext.py
- mopidy/internal/deps.py
- setup.cfg
- tests/internal/test_deps.py
- tests/test_ext.py
- Use `importlib.metadata` on Python 3.10+, and `importlib_metadata` only as a fallback on older Python versions.
- Fix infinite loop in test case when deps with dash in their name is installed.
FYI @janiversen
> Use stdlib's importlib on Python 3.10+

- docs/conf.py
- mopidy/__main__.py
- mopidy/commands.py
- mopidy/config/__init__.py
- setup.cfg
This PR modernizes the Sphinx setup a bit to get to the point where `sphinx-autodoc-typehints` can successfully build API docs with type hints.
> Show type hints in API docs

- mopidy/audio/actor.py
- mopidy/audio/listener.py
- mopidy/audio/utils.py
- mopidy/backend.py
- mopidy/commands.py
- mopidy/core/actor.py
- mopidy/core/history.py
- mopidy/core/library.py
- mopidy/core/listener.py
- mopidy/core/mixer.py
- mopidy/core/playback.py
- mopidy/core/playlists.py
- mopidy/core/tracklist.py
- mopidy/internal/validation.py
- mopidy/mixer.py
- mopidy/models/__init__.py
- mopidy/models/fields.py
- mopidy/types.py
- pyproject.toml
This adds type hints to all of the Core API, which will hopefully be helpful in both Core API tests and frontends.
---
Example of type hints in action in VS Code in the Core API test suite. The `dict[str, tuple[Image, ...]]` part is visually inserted by VS Code on the fly.
> Type the Core API

- docs/history/changelog-0.x.rst
Typos fixed in docs/history/changelog-0.x.rst file.
> Fixed tyos in changelog-0.x.rst file

- README.rst
I have noticed some grammatical mistakes in **README** inside section "**Mopidy on Raspberry Pi**" and "**Mopidy is hackable**"
"**The Raspberry Pi is an popular device**"  should be "**The Raspberry Pi is a popular device**"
" **and is used to control playback**"  should be " **and are used to control playback**"
Screenshot-
> Update README.rst - fix two grammar issues.

- docs/api/backend.rst
- docs/changelog.rst
- mopidy/audio/actor.py
- mopidy/internal/deps.py
- tests/audio/test_actor.py
- tests/dummy_audio.py
This has previously been used by Mopidy-Spotify. Removing this will make
it easier to maintain the remaining audio layer because there will be
fewer corner cases to think about and test.
Fixes #2114
> Remove appsrc support

- docs/changelog.rst
- docs/devenv.rst
- mopidy/internal/gi.py
- setup.cfg
This makes PyGObject (the `gi` module) an explicit dependency, so that we no longer need to make sure our development virtualenv is created with `--system-site-packages` to get access to the globally installed PyGObject (`python3-gi` on Debian/Ubuntu).
The only downside I can think of right now is that extensions, which depends on Mopidy, will have to have PyGObject's system library dependencies installed to be able to run tests. As long as they make use of the `mopidy/ci:latest` image to run tests on CI, this should already be handled for them.
> PyGObject as explicit dependency

- src/mopidy/backend.py
Ref discussion at https://github.com/mopidy/mopidy/commit/06fea20b96acd1bcdbef01d7eb2a85900ae9294f#r134689375 it looks like we've had a wrong type and default implementation in this method for a long time.
> Fix backend.library.search() return type and default impl

- src/mopidy/config/types.py
- src/mopidy/internal/jsonrpc.py
- src/mopidy/internal/path.py
- src/mopidy/internal/xdg.py
- tests/internal/test_path.py
This makes the types of the following modules pass pyright in strict mode:
- `mopidy.internal.path`
- `mopidy.internal.xdg`
- `mopidy.internal.jsonrpc`
> Stricter types

- docs/changelog.rst
- src/mopidy/internal/deps.py
- tests/internal/test_deps.py
- Do not repeat transitive dependencies.
- Refactor to use dataclass instead of dicts.
```diff
--- before.txt  2024-02-23 19:58:31.779994186 +0100
+++ after.txt   2024-02-23 19:58:37.528000081 +0100
@@ -1,7 +1,7 @@
Executable: /home/jodal/mopidy-dev/.venv/bin/mopidy
Platform: Linux-6.6.15-amd64-x86_64-with-glibc2.37
Python: CPython 3.11.8 from /usr/lib/python3.11
-Mopidy: 4.0.0a1 from /home/jodal/mopidy-dev/.venv/lib/python3.11/site-packages
+mopidy: 4.0.0a1 from /home/jodal/mopidy-dev/.venv/lib/python3.11/site-packages
pygobject: 3.46.0 from /home/jodal/mopidy-dev/.venv/lib/python3.11/site-packages
pycairo: 1.26.0 from /home/jodal/mopidy-dev/.venv/lib/python3.11/site-packages
pykka: 4.0.2 from /home/jodal/mopidy-dev/.venv/lib/python3.11/site-packages
@@ -13,31 +13,14 @@
certifi: 2024.2.2 …
```
> Refactor deps command

- docs/changelog.rst
- src/mopidy/core/playback.py
- src/mopidy/internal/deprecation.py
- tests/core/test_playback.py
This argument has been deprecated since Mopidy 3.0, released more than four years ago.
I don't know how much this argument is used by frontends/clients. However, the migration path is straight forward as any caller can replace:
```python
core.playback.play(tl_track)
```
With:
```python
core.playback.play(tl_track.tlid)
```
Or, to keep compatibility with Mopidy < 4.0:
```python
core.playback.play(tlid=tl_track.tlid)
```
The recently added type hints should also be of help when migrating frontends/clients.
Part of #1855
> Remove core.playback.play()'s tl_track argument

- README.rst
- docs/changelog.rst
- docs/contributing.rst
- docs/devenv.rst
- docs/extensiondev.rst
- docs/releasing.rst
This PR does the necessary documentation updates to drop `develop` branch and
just use `main` for development.
- The change rate to core naturally decreased with all the extensions we moved
out during the Python 3 porting.
- The change rate to core is in general quite low these days.
- The `git flow` workflow have a lot less mindshare than what it had when we
started using this branch layout.
- Mopidy core will have an identical branch setup to all of Mopidy's extensions.
- Less education of potential contributors.
The main drawback is that if we spend a long while on a big release, we have to
create explicit bugfix release branches and cherry-pick fixes that might be
released earlier than the big release.
I don't really see this as a drawback, as this moves the responsibility for …
> Switch to main as the integration branch

- docs/changelog.rst
- src/mopidy/backend.py
- src/mopidy/core/library.py
- tests/backend/test_backend.py
- tests/core/test_library.py
- tests/core/test_playback.py
- tests/core/test_tracklist.py
- tests/dummy_backend.py
Resolves #2116.
Adds `Backend.lookup_many()` as a replacement method to `Backend.lookup` which accepts a of URIs instead a single URI so that calls can be batched instead of done sequentially. Also reflects these in changes `core.LibraryController.lookup` to pass in the list of URIs it receives instead of calling `Backend.lookup` individually for each URI. Provides a default implementation for `Backend.lookup_many` to call `Backend.lookup` individually to preserve backwards compatibility with existing backends.
> Modify Backend.lookup to accept list of URIs 

- docs/running/service.rst
Refs: #1974
After I upgraded my Mopidy host to a Raspberry Pi 5, I installed Debian Bookworm and had to reconfigure Mopidy as a service. I suggest to document how to configure PipeWire and Mopidy to work together.
> Document use as service with PipeWire

- docs/clients.rst
Add 'Mopicon' Flutter standalone application to list of available clients.
> Add Mopicon to list of standalone applications

- README.rst
Changed link to pimusicbox to the project's github page instead of, now defunct, webpage.
The old url for pimusicbox must have been purchased by another company. At best its a gambling site at worst it's hosting malware.
> Update README.rst to stop sending people to gambling site

- pyproject.toml
Seeing as CI fails to build newer versions of `pygobject`, this pins it to the 3.50.0 version [that does seem to pass CI](https://github.com/mopidy/mopidy/actions/runs/13718677504/job/38369038069).
See https://github.com/akx/mopidy/pull/1 to see this passing on my fork.
> Pin pygobject for now

- pyproject.toml
- src/mopidy/core/library.py
- src/mopidy/http/actor.py
This PR upgrades Ruff from 0.9.9 to 0.11.0, [disables one noisy rule](https://docs.astral.sh/ruff/rules/runtime-cast-value/) and fixes the rest. (That `logging.error` was a good catch from [`LOG015`](https://docs.astral.sh/ruff/rules/root-logger-call/)).
> Upgrade Ruff

- src/mopidy/audio/scan.py
I think this has the wrong cast. We extract the `Gst.Structure` from the `Gst.Caps` in our have-type handler.
> audio: fix 'have-type' event caps typing

- docs/devenv.rst
This one is better as it also works with `uv pip`.
> docs: alternate method to install dev tools with pip
