mopidy/mopidy

- mopidy/core/actor.py
- mopidy/core/playback.py
- mopidy/core/playlists.py
- mopidy/core/tracklist.py
- mopidy/utils/deprecation.py
> Deprecate properties in the Core API

- mopidy/audio/scan.py
- mopidy/core/actor.py
- mopidy/local/search.py
- mopidy/models.py
- setup.cfg
- tests/mpd/test_commands.py
Fix the 'lambda to def' warnings
> flake8: fix PEP8 warnings about lambda

- mopidy/core/mixer.py
- mopidy/mixer.py
- tests/core/test_mixer.py
- tests/mpd/protocol/__init__.py
- tests/mpd/test_status.py
- tests/utils/test_jsonrpc.py
> Remove test-only code

- mopidy/core/actor.py
- mopidy/core/tracklist.py
- mopidy/local/search.py
Fixes "W503 line break before binary operator"
> Fix flake8 tests

- docs/installation/arch.rst
> Revert "Update arch.rst"

- docs/changelog.rst
- mopidy/core/playback.py
- tests/core/test_playback.py
- tests/local/test_playback.py
Do not switch state from paused to playing when seeking
Fixes #939
> Don't change to playing state when seeking in paused state

- tests/core/test_playback.py
Add some more test cases for PlaybackController
> Add tests for PlaybackController get_current_(tl_)track

- mopidy/core/mixer.py
- mopidy/mpd/protocol/audio_output.py
- mopidy/mpd/protocol/playback.py
- tests/core/test_mixer.py
- tests/mpd/protocol/test_audio_output.py
> None-mixer adjustments

- mopidy/audio/actor.py
> Audio buffering cleanups

- docs/conf.py
- docs/contributing.rst
- docs/devenv.rst
- docs/devtools.rst
- docs/index.rst
- docs/installation/index.rst
- docs/releasing.rst
> New contribution page and development environment guide

- docs/versioning.rst
> docs: Add section on semantic versioning

- docs/changelog.rst
- mopidy/core/playback.py
- mopidy/core/tracklist.py
> core: Make tracklist.mark_*() private

- .travis.yml
- tests/audio/test_scan.py
This is an experiment to test the new build infrastructure. I'll retrigger the build or amend the commit whenever there's progress either from Travis or our side towards a working setup.
> travis: Use new faster build infrastructure

- docs/changelog.rst
- mopidy/core/library.py
- mopidy/core/playlists.py
- tests/core/test_library.py
- tests/core/test_playlists.py
> Make core more robust

- docs/api/models.rst
- docs/changelog.rst
- mopidy/models.py
- mopidy/utils/deprecation.py
- tests/models/test_fields.py
- tests/models/test_models.py
> Improve models memory usage

- mopidy/commands.py
- mopidy/core/actor.py
> core: Get access to config

- docs/changelog.rst
- mopidy/audio/scan.py
- mopidy/local/commands.py
- tests/audio/test_scan.py
Likely fixes #726. Sadly my plan for fixing #797 falls a bit short, as only having the scanner handle it won't do much good.
> Improve audio scanner robustness

- docs/changelog.rst
- mopidy/core/library.py
- mopidy/core/mixer.py
- mopidy/core/playback.py
- mopidy/core/playlists.py
- mopidy/core/tracklist.py
- mopidy/exceptions.py
- mopidy/mpd/protocol/current_playlist.py
- mopidy/mpd/protocol/music_db.py
- mopidy/utils/validation.py
- tests/local/test_library.py
- tests/local/test_playback.py
- tests/mpd/test_status.py
- tests/utils/test_validation.py
Should cover most of #700 - changelog outstanding, but it's time for bed now...
> Validate core inputs

- mopidy/mpd/protocol/audio_output.py
- mopidy/mpd/protocol/current_playlist.py
- mopidy/mpd/protocol/music_db.py
- mopidy/mpd/protocol/playback.py
- mopidy/mpd/protocol/reflection.py
- mopidy/mpd/protocol/status.py
No functional changes, so don't think this warrants a changelog entry?
> MPD spring cleaning

- docs/changelog.rst
- mopidy/core/playback.py
- mopidy/utils/deprecation.py
- tests/core/test_playback.py
Very much bare bones, but just enough to get this into 1.1 in a basic form.
> core: Add play(tlid) support

- docs/changelog.rst
- mopidy/mpd/uri_mapper.py
- tests/mpd/protocol/test_regression.py
> Fix MPD playlist name clobbering

- docs/changelog.rst
- mopidy/audio/actor.py
- tests/mpd/protocol/test_regression.py
> V1.0.x fixes for #1146 and #1147

- mopidy/__main__.py
- mopidy/backend.py
- mopidy/commands.py
- mopidy/core/actor.py
- mopidy/mixer.py
Builds on part 1 pull request and will be rebased if further changes are made there.
> Remainder of the startup cleanups

- docs/changelog.rst
- mopidy/core/playback.py
- tests/core/test_playback.py
> core: Make sure track gets changed while paused

- docs/changelog.rst
- mopidy/core/listener.py
- mopidy/core/playlists.py
- mopidy/m3u/playlists.py
- tests/core/test_events.py
- tests/core/test_listener.py
Fixes #996. Tests are provided.
> Implemented playlist_deleted event triggering

- mopidy/m3u/playlists.py
- mopidy/m3u/translator.py
- tests/m3u/test_translator.py
Unicode is nice, let's support it!
> Support loading of m3u8 playlists.

- docs/changelog.rst
- mopidy/file/library.py
> file: Adjust file/media_dirs failure logging

- docs/changelog.rst
- mopidy/file/library.py
> file: Don't scan files on browsing

- docs/changelog.rst
- mopidy/file/library.py
> file: Allow lookup() of any file URI

- docs/changelog.rst
- mopidy/http/actor.py
- mopidy/mpd/actor.py
- mopidy/zeroconf.py
I deemed these changes a bit too large for 1.1.2, so pull request against develop intentionally.
> Fix #1283: Zeroconf hostname/interface management

- docs/changelog.rst
- docs/clients/mpd.rst
- docs/clients/mpris.rst
- docs/clients/upnp.rst
- docs/codestyle.rst
- docs/conf.py
- docs/config.rst
- docs/devenv.rst
- docs/ext/backends.rst
- docs/ext/web.rst
- docs/extensiondev.rst
- docs/installation/raspberrypi.rst
- docs/running.rst
- tox.ini
https://github.com/mopidy/mopidy/issues/1236
> Run sphinx linkcheck in tox. Fixes for a bunch of broken links.

- .travis.yml
Don't merge: I need this pull request to stay open to have a place to test Travis configuration changes without filling develop with noisy commits.
> travis: Test on Ubuntu 14.04 infrastructure

- mopidy/mpd/exceptions.py
- mopidy/mpd/protocol/stored_playlists.py
- mopidy/mpd/uri_mapper.py
- tests/mpd/protocol/test_regression.py
- tests/mpd/protocol/test_stored_playlists.py
Fixes #1348 and generally improves testing of error cases related to playlist editing.
> MPD playlist editing error handling

- docs/changelog.rst
- mopidy/mpd/protocol/playback.py
- tests/mpd/protocol/test_playback.py
I think this is such a simple change (and it unbreaks at least mpc) that it can go into the next 1.1 release.
> MPD: Add volume command

- docs/extensiondev.rst
Contains the proposed documentation improvements outlined in #503.
> Draft documentation on how to test extensions.

- docs/extensiondev.rst
Fixes a typo in the test code samples that was spotted by @ZenithDK.
> Fix typo in code sample

- docs/changelog.rst
- docs/ext/m3u.rst
- mopidy/m3u/__init__.py
- mopidy/m3u/ext.conf
- mopidy/m3u/playlists.py
- tests/m3u/test_playlists.py
As discussed in #1428...
Please review and feel free to edit at your own discretion to get this merged in time for v2.0.0, since I'll probably be offline for the rest of V-Day ;-)
> Fix #1428: Add m3u/base_dir confval.

- mopidy/core/playback.py
- mopidy/core/tracklist.py
- tests/core/test_playback.py
> Unmerged fixes and tests from 1.1

- docs/changelog.rst
- mopidy/file/library.py
- mopidy/internal/path.py
- tests/internal/test_path.py
> file: Fix crash when media_dirs contains non-ASCII chars

- mopidy/audio/tags.py
- tests/audio/test_tags.py
> If the date in a tag is invalid, skip it

- docs/ext/file.rst
I submitted this against branch `develop`, let me know if you need me to rebase against master.
> Fix a name in file.rst.

- mopidy/local/storage.py
> Change error wording

- mopidy/file/__init__.py
- mopidy/file/ext.conf
- mopidy/file/library.py
Added support for excluding specific file extensions from Mopidy-File
library, using same scheme as Mopidy-Local
> Mopidy-File: Added ability to exclude files by extension

- README.rst
> Tiny grammar mistake

- docs/ext/http.rst
Replace "takes care or user authentication" with "takes care of user authentication".
> Fix spelling mistake

- docs/ext/backends.rst
Register new Mopidy backend extension for Yandex.Disk
> Add Yandex.Disk backend

- docs/changelog.rst
- mopidy/audio/actor.py
- mopidy/internal/deprecation.py
- tests/dummy_audio.py
> audio: Remove deprecated audio APIs

- docs/api/js.rst
- docs/changelog.rst
- docs/ext/http.rst
- mopidy/http/__init__.py
- mopidy/http/actor.py
- mopidy/http/ext.conf
- tests/http/test_server.py
> http: Remove http/static_dir support

- docs/changelog.rst
- mopidy/backend.py
- mopidy/internal/deprecation.py
- mopidy/local/__init__.py
- mopidy/models/__init__.py
- mopidy/models/immutable.py
- mopidy/mpd/translator.py
- tests/audio/test_tags.py
- tests/backend/test_backend.py
- tests/local/test_library.py
- tests/models/test_models.py
- tests/mpd/test_translator.py
> Remove deprecated model APIs

- mopidy/compat.py
- mopidy/internal/jsonrpc.py
- tests/internal/test_jsonrpc.py
- tox.ini
Also removed some of the other deselected tests that already pass OK.
> Py3: JsonRPC

- mopidy/http/handlers.py
- tests/http/test_server.py
- tox.ini
> Py3: http frontend

- mopidy/file/library.py
- tox.ini
This was broken in #1814 but not noticed since the tests were
skipped.
> Py3: Fixed file lookup test

- mopidy/audio/actor.py
- mopidy/audio/tags.py
- mopidy/core/actor.py
- mopidy/file/library.py
- mopidy/internal/storage.py
- tests/audio/test_scan.py
- tests/audio/test_tags.py
- tests/core/test_actor.py
- tox.ini
1447 passed, 552 deselected: 72% green tests on Python 3!
> py3: Convert mopidy.{audio,core}

- mopidy/m3u/playlists.py
- mopidy/m3u/translator.py
- tests/m3u/test_playlists.py
- tests/m3u/test_translator.py
- tox.ini
> Py3: Convert m3u

- mopidy/commands.py
- mopidy/config/__init__.py
- mopidy/config/types.py
- mopidy/internal/playlists.py
- tests/config/test_types.py
Ref. the discussion in #1850.
I also fixed an issue with the versions list in the config file header.
> Fix dubious uses of byte literals

- docs/changelog.rst
Finally read to the end of that huge changelog. A few suggested tweaks.
> docs: changelog tweaks

- docs/installation/fedora.rst
- docs/installation/pypi.rst
Finally, all has landed in stable repositories. I'm open to changes in the wording.
> Fedora installation instructions

- .deepsource.toml
- MANIFEST.in
- mopidy/audio/actor.py
- mopidy/commands.py
- mopidy/core/library.py
- mopidy/internal/validation.py
- tests/core/test_library.py
- Fix dangerous default argument
- Remove unnecessary comprehension
- Use literal syntax instead of function calls to create the data structure
---
Find the other issues found here - [https://deepsource.io/gh/pnijhara/mopidy/issues/?category=all](https://deepsource.io/gh/pnijhara/mopidy/issues/?category=all)
This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. …
> Fix some code quality and bug-risk issues

- mopidy/audio/utils.py
- mopidy/core/actor.py
- mopidy/core/playback.py
- mopidy/core/tracklist.py
- mopidy/ext.py
> removing assert statement used outside of tests

- mopidy/audio/actor.py
- mopidy/backend.py
- tests/audio/test_actor.py
- tests/core/test_playback.py
- tests/dummy_audio.py
Hi. This is meant to be a workable implementation @belak's #1608.
@kingosticks Is this the kind of thing you had in mind?
> Add download_buffering() option to PlaybackProvider

- mopidy/core/history.py
- mopidy/internal/deps.py
- mopidy/internal/process.py
> fix: Remove unnecessary comprehensions

- mopidy/ext.py
> Fix startup crash when loading invalid extensions

- docs/api/backend.rst
- docs/api/http-server.rst
- docs/extensiondev.rst
- Update a couple of URLs to use HTTPS
- Minor grammar improvement in soundcloud reference
> Minor docs updates

- mopidy/core/history.py
- tests/core/test_history.py
@kingosticks  Reopened PR for issue #1991  for previously closed PR #2011 
Review it, and give me a go ahead for actual implementation in main program
> fix: TypeError exception when playing track with unnamed artists  #1991 

- mopidy/config/types.py
> types: flake8 fix

- docs/clients.rst
See https://mopidy.zulipchat.com/#narrow/stream/207265-mopidy-dev/topic/New.20client/near/314419823
> docs: add standalone clients section in clients.rst

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/ubuntu-devel.yml
- docs/conf.py
- mopidy/core/actor.py
- mopidy/core/library.py
- mopidy/core/tracklist.py
- mopidy/file/__init__.py
- mopidy/http/handlers.py
- mopidy/internal/deprecation.py
- mopidy/m3u/__init__.py
- mopidy/softwaremixer/__init__.py
- mopidy/softwaremixer/mixer.py
- mopidy/stream/__init__.py
- tests/core/test_playback.py
- tests/stream/test_playback.py
- tests/test_ext.py
- tox.ini
> Fix and upgrade CI workflows

- docs/installation/pypi.rst
- docs/installation/raspberrypi.rst
- Update PyPI installation docs
- Add warning to Raspberry Pi install docs
> Update PyPI installation docs

- docs/contributing.rst
- docs/devenv.rst
- Remove branch naming guidelines
- Update devenv docs
> Update contribution docs

- pyproject.toml
- src/mopidy/http/handlers.py
- src/mopidy/internal/jsonrpc.py
- tests/http/test_events.py
- tests/internal/test_jsonrpc.py
Lifting more non-controversial changes from the msgspec PR to reduce the diff.
> JSON-RPC refactor

- src/mopidy/internal/deps.py
I'm in two minds about this. Currently for spotifyaudiosrc, given that it's not officially packaged, it's useful to know the version you have installed. But for every other element, it's going to just be the same as the base gstremer version. Maybe we could only print it if it differed from the Gstreamer version?  
```
GStreamer: 1.24.2.0 from /home/nick/Dev/mopidy-dev/.venv/lib/python3.12/site-packages/gi
Detailed information: 
Python wrapper: python-gi 3.50.0
Relevant elements:
Found:
uridecodebin: 1.24.2
souphttpsrc: 1.24.2
spotifyaudiosrc: 0.14.0-alpha.1-335dbdd
alsasink: 1.24.2
osssink: 1.24.2
oss4sink: 1.24.2
pulsesink: 1.24.2
id3demux: 1.24.2
id3v2mux: 1.24.2
lamemp3enc: 1.24.2
mpegaudioparse: 1.24.2
mpg123audiodec: 1.24.2
vorbisdec: 1.24.2
vorbisenc: 1.24.2
vorbisparse: 1.24.2 …
```
> deps: show Gst element versions

- .github/workflows/ci.yml
- .readthedocs.yml
- pyproject.toml
- src/mopidy/core/playlists.py
Including using tox-uv to run checks both locally and in CI.
> Update pyproject.toml and CI workflow to match new cookiecutter

- docs/extensiondev.rst
- docs/releasing.rst
The downside of having been so detailed back in the days is that there's a lot to keep up to date. Tried to find the right balance between removing and updating here.
This PR goes hand in hand with mopidy/mopidy-ext-template#26.
> docs: Extension dev and release docs revision

- docs/changelog.rst
- src/mopidy/audio/scan.py
Builds on https://github.com/mopidy/mopidy/pull/2200. Fixes https://github.com/mopidy/mopidy/issues/2199
> Fix get structure get name
